# Generated by Django 5.1 on 2024-08-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vestido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estilo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('talla', models.IntegerField()),
            ],
        ),
    ]
